# FILE: universe.py

"""
Universe definition: ticker -> (display_name, theme/sector)

Core mode (pipeline.active_universe) ตัด N ตัวแรกของแต่ละตลาด
ดังนั้นลำดับใน dict มีความหมาย: US 40 ตัวแรกเป็นหุ้นใหญ่/สภาพคล่องสูง

Yahoo Finance ticker conventions:
  US : plain symbol (Berkshire = BRK-B)
  TH : SYMBOL.BK
  HK : 4-digit code + .HK
  JP : 4-digit code + .T
  KR : 6-digit code + .KS
  CN : 6-digit code + .SS (Shanghai) / .SZ (Shenzhen)
  DE : SYMBOL.DE (XETRA)
  FR : SYMBOL.PA (Euronext Paris)
  GB : SYMBOL.L (London Stock Exchange)
"""
from etf_meta import ETF_META

UNIVERSE = {
    "US": {
        # --- core 40 (pipeline CORE_N["US"]) ---
        'AAPL': ('Apple Inc.', 'Information Technology'),
        'MSFT': ('Microsoft', 'Information Technology'),
        'NVDA': ('Nvidia', 'Information Technology'),
        'AMZN': ('Amazon', 'Consumer Discretionary'),
        'GOOGL': ('Alphabet Inc. (Class A)', 'Communication Services'),
        'META': ('Meta Platforms', 'Communication Services'),
        'TSLA': ('Tesla, Inc.', 'Consumer Discretionary'),
        'AVGO': ('Broadcom', 'Information Technology'),
        'BRK-B': ('Berkshire Hathaway', 'Financials'),
        'JPM': ('JPMorgan Chase', 'Financials'),
        'LLY': ('Lilly (Eli)', 'Health Care'),
        'UNH': ('UnitedHealth Group', 'Health Care'),
        'XOM': ('ExxonMobil', 'Energy'),
        'JNJ': ('Johnson & Johnson', 'Health Care'),
        'V': ('Visa Inc.', 'Financials'),
        'MA': ('Mastercard', 'Financials'),
        'COST': ('Costco', 'Consumer Staples'),
        'HD': ('Home Depot (The)', 'Consumer Discretionary'),
        'PG': ('Procter & Gamble', 'Consumer Staples'),
        'WMT': ('Walmart', 'Consumer Staples'),
        'NFLX': ('Netflix', 'Communication Services'),
        'ORCL': ('Oracle Corporation', 'Information Technology'),
        'AMD': ('Advanced Micro Devices', 'Information Technology'),
        'KO': ('Coca-Cola Company (The)', 'Consumer Staples'),
        'ABBV': ('AbbVie', 'Health Care'),
        'CRM': ('Salesforce', 'Information Technology'),
        'BAC': ('Bank of America', 'Financials'),
        'PEP': ('PepsiCo', 'Consumer Staples'),
        'CVX': ('Chevron Corporation', 'Energy'),
        'TMO': ('Thermo Fisher Scientific', 'Health Care'),
        'CSCO': ('Cisco', 'Information Technology'),
        'ADBE': ('Adobe Inc.', 'Information Technology'),
        'MCD': ("McDonald's", 'Consumer Discretionary'),
        'ACN': ('Accenture', 'Information Technology'),
        'LIN': ('Linde plc', 'Materials'),
        'ABT': ('Abbott Laboratories', 'Health Care'),
        'GE': ('GE Aerospace', 'Industrials'),
        'CAT': ('Caterpillar Inc.', 'Industrials'),
        'IBM': ('IBM', 'Information Technology'),
        'NOW': ('ServiceNow', 'Information Technology'),
        # --- remainder ---
        'MMM': ('3M', 'Industrials'),
        'AOS': ('A. O. Smith', 'Industrials'),
        'AES': ('AES Corporation', 'Utilities'),
        'AFL': ('Aflac', 'Financials'),
        'A': ('Agilent Technologies', 'Health Care'),
        'APD': ('Air Products', 'Materials'),
        'ABNB': ('Airbnb', 'Consumer Discretionary'),
        'AKAM': ('Akamai Technologies', 'Information Technology'),
        'ALB': ('Albemarle Corporation', 'Materials'),
        'ARE': ('Alexandria Real Estate Equities', 'Real Estate'),
        'ALGN': ('Align Technology', 'Health Care'),
        'ALLE': ('Allegion', 'Industrials'),
        'LNT': ('Alliant Energy', 'Utilities'),
        'ALL': ('Allstate', 'Financials'),
        'MO': ('Altria', 'Consumer Staples'),
        'AMCR': ('Amcor', 'Materials'),
        'AEE': ('Ameren', 'Utilities'),
        'AEP': ('American Electric Power', 'Utilities'),
        'AXP': ('American Express', 'Financials'),
        'AIG': ('American International Group', 'Financials'),
        'AMT': ('American Tower', 'Real Estate'),
        'AWK': ('American Water Works', 'Utilities'),
        'AMP': ('Ameriprise Financial', 'Financials'),
        'AME': ('Ametek', 'Industrials'),
        'AMGN': ('Amgen', 'Health Care'),
        'APH': ('Amphenol', 'Information Technology'),
        'ADI': ('Analog Devices', 'Information Technology'),
        'AON': ('Aon plc', 'Financials'),
        'APA': ('APA Corporation', 'Energy'),
        'APO': ('Apollo Global Management', 'Financials'),
        'AMAT': ('Applied Materials', 'Information Technology'),
        'APP': ('AppLovin', 'Information Technology'),
        'APTV': ('Aptiv', 'Consumer Discretionary'),
        'ACGL': ('Arch Capital Group', 'Financials'),
        'ADM': ('Archer Daniels Midland', 'Consumer Staples'),
        'ARES': ('Ares Management', 'Financials'),
        'ANET': ('Arista Networks', 'Information Technology'),
        'AJG': ('Arthur J. Gallagher & Co.', 'Financials'),
        'AIZ': ('Assurant', 'Financials'),
        'T': ('AT&T', 'Communication Services'),
        'ATO': ('Atmos Energy', 'Utilities'),
        'ADSK': ('Autodesk', 'Information Technology'),
        'ADP': ('Automatic Data Processing', 'Industrials'),
        'AZO': ('AutoZone', 'Consumer Discretionary'),
        'AVB': ('AvalonBay Communities', 'Real Estate'),
        'AVY': ('Avery Dennison', 'Materials'),
        'AXON': ('Axon Enterprise', 'Industrials'),
        'BKR': ('Baker Hughes', 'Energy'),
        'BALL': ('Ball Corporation', 'Materials'),
        'BAX': ('Baxter International', 'Health Care'),
        'BDX': ('Becton Dickinson', 'Health Care'),
        'BBY': ('Best Buy', 'Consumer Discretionary'),
        'TECH': ('Bio-Techne', 'Health Care'),
        'BIIB': ('Biogen', 'Health Care'),
        'BLK': ('BlackRock', 'Financials'),
        'BX': ('Blackstone Inc.', 'Financials'),
        'XYZ': ('Block, Inc.', 'Financials'),
        'BNY': ('BNY Mellon', 'Financials'),
        'BA': ('Boeing', 'Industrials'),
        'BKNG': ('Booking Holdings', 'Consumer Discretionary'),
        'BSX': ('Boston Scientific', 'Health Care'),
        'BMY': ('Bristol Myers Squibb', 'Health Care'),
        'BR': ('Broadridge Financial Solutions', 'Industrials'),
        'BRO': ('Brown & Brown', 'Financials'),
        'BF.B': ('Brown–Forman', 'Consumer Staples'),
        'BLDR': ('Builders FirstSource', 'Industrials'),
        'BG': ('Bunge Global', 'Consumer Staples'),
        'BXP': ('BXP, Inc.', 'Real Estate'),
        'CHRW': ('C.H. Robinson', 'Industrials'),
        'CDNS': ('Cadence Design Systems', 'Information Technology'),
        'CPT': ('Camden Property Trust', 'Real Estate'),
        'CPB': ("Campbell's Company (The)", 'Consumer Staples'),
        'COF': ('Capital One', 'Financials'),
        'CAH': ('Cardinal Health', 'Health Care'),
        'CCL': ('Carnival Corporation', 'Consumer Discretionary'),
        'CARR': ('Carrier Global', 'Industrials'),
        'CVNA': ('Carvana', 'Consumer Discretionary'),
        'CASY': ("Casey's", 'Consumer Staples'),
        'CBOE': ('Cboe Global Markets', 'Financials'),
        'CBRE': ('CBRE Group', 'Real Estate'),
        'CDW': ('CDW Corporation', 'Information Technology'),
        'COR': ('Cencora', 'Health Care'),
        'CNC': ('Centene Corporation', 'Health Care'),
        'CNP': ('CenterPoint Energy', 'Utilities'),
        'CF': ('CF Industries', 'Materials'),
        'CRL': ('Charles River Laboratories', 'Health Care'),
        'SCHW': ('Charles Schwab Corporation', 'Financials'),
        'CHTR': ('Charter Communications', 'Communication Services'),
        'CMG': ('Chipotle Mexican Grill', 'Consumer Discretionary'),
        'CB': ('Chubb Limited', 'Financials'),
        'CHD': ('Church & Dwight', 'Consumer Staples'),
        'CIEN': ('Ciena', 'Information Technology'),
        'CI': ('Cigna', 'Health Care'),
        'CINF': ('Cincinnati Financial', 'Financials'),
        'CTAS': ('Cintas', 'Industrials'),
        'C': ('Citigroup', 'Financials'),
        'CFG': ('Citizens Financial Group', 'Financials'),
        'CLX': ('Clorox', 'Consumer Staples'),
        'CME': ('CME Group', 'Financials'),
        'CMS': ('CMS Energy', 'Utilities'),
        'CTSH': ('Cognizant', 'Information Technology'),
        'COHR': ('Coherent Corp.', 'Information Technology'),
        'COIN': ('Coinbase', 'Financials'),
        'CL': ('Colgate-Palmolive', 'Consumer Staples'),
        'CMCSA': ('Comcast', 'Communication Services'),
        'FIX': ('Comfort Systems USA', 'Industrials'),
        'CAG': ('Conagra Brands', 'Consumer Staples'),
        'COP': ('ConocoPhillips', 'Energy'),
        'ED': ('Consolidated Edison', 'Utilities'),
        'STZ': ('Constellation Brands', 'Consumer Staples'),
        'CEG': ('Constellation Energy', 'Utilities'),
        'COO': ('Cooper Companies (The)', 'Health Care'),
        'CPRT': ('Copart', 'Industrials'),
        'GLW': ('Corning Inc.', 'Information Technology'),
        'CPAY': ('Corpay', 'Financials'),
        'CTVA': ('Corteva', 'Materials'),
        'CSGP': ('CoStar Group', 'Real Estate'),
        'CRH': ('CRH plc', 'Materials'),
        'CRWD': ('CrowdStrike', 'Information Technology'),
        'CCI': ('Crown Castle', 'Real Estate'),
        'CSX': ('CSX Corporation', 'Industrials'),
        'CMI': ('Cummins', 'Industrials'),
        'CVS': ('CVS Health', 'Health Care'),
        'DHR': ('Danaher Corporation', 'Health Care'),
        'DRI': ('Darden Restaurants', 'Consumer Discretionary'),
        'DDOG': ('Datadog', 'Information Technology'),
        'DVA': ('DaVita', 'Health Care'),
        'DECK': ('Deckers Brands', 'Consumer Discretionary'),
        'DE': ('Deere & Company', 'Industrials'),
        'DELL': ('Dell Technologies', 'Information Technology'),
        'DAL': ('Delta Air Lines', 'Industrials'),
        'DVN': ('Devon Energy', 'Energy'),
        'DXCM': ('Dexcom', 'Health Care'),
        'FANG': ('Diamondback Energy', 'Energy'),
        'DLR': ('Digital Realty', 'Real Estate'),
        'DG': ('Dollar General', 'Consumer Staples'),
        'DLTR': ('Dollar Tree', 'Consumer Staples'),
        'D': ('Dominion Energy', 'Utilities'),
        'DPZ': ("Domino's", 'Consumer Discretionary'),
        'DASH': ('DoorDash', 'Consumer Discretionary'),
        'DOV': ('Dover Corporation', 'Industrials'),
        'DOW': ('Dow Inc.', 'Materials'),
        'DHI': ('D. R. Horton', 'Consumer Discretionary'),
        'DTE': ('DTE Energy', 'Utilities'),
        'DUK': ('Duke Energy', 'Utilities'),
        'DD': ('DuPont', 'Materials'),
        'ETN': ('Eaton Corporation', 'Industrials'),
        'EBAY': ('eBay Inc.', 'Consumer Discretionary'),
        'SATS': ('EchoStar', 'Communication Services'),
        'ECL': ('Ecolab', 'Materials'),
        'EIX': ('Edison International', 'Utilities'),
        'EW': ('Edwards Lifesciences', 'Health Care'),
        'EA': ('Electronic Arts', 'Communication Services'),
        'ELV': ('Elevance Health', 'Health Care'),
        'EME': ('Emcor', 'Industrials'),
        'EMR': ('Emerson Electric', 'Industrials'),
        'ETR': ('Entergy', 'Utilities'),
        'EOG': ('EOG Resources', 'Energy'),
        'EQT': ('EQT Corporation', 'Energy'),
        'EFX': ('Equifax', 'Industrials'),
        'EQIX': ('Equinix', 'Real Estate'),
        'EQR': ('Equity Residential', 'Real Estate'),
        'ERIE': ('Erie Indemnity', 'Financials'),
        'ESS': ('Essex Property Trust', 'Real Estate'),
        'EL': ('Estée Lauder Companies (The)', 'Consumer Staples'),
        'EG': ('Everest Group', 'Financials'),
        'EVRG': ('Evergy', 'Utilities'),
        'ES': ('Eversource Energy', 'Utilities'),
        'EXC': ('Exelon', 'Utilities'),
        'EXE': ('Expand Energy', 'Energy'),
        'EXPE': ('Expedia Group', 'Consumer Discretionary'),
        'EXPD': ('Expeditors International', 'Industrials'),
        'EXR': ('Extra Space Storage', 'Real Estate'),
        'FFIV': ('F5, Inc.', 'Information Technology'),
        'FDS': ('FactSet', 'Financials'),
        'FICO': ('Fair Isaac', 'Information Technology'),
        'FAST': ('Fastenal', 'Industrials'),
        'FRT': ('Federal Realty Investment Trust', 'Real Estate'),
        'FDX': ('FedEx', 'Industrials'),
        'FDXF': ('FedEx Freight', 'Industrials'),
        'FIS': ('Fidelity National Information Services', 'Financials'),
        'FITB': ('Fifth Third Bancorp', 'Financials'),
        'FSLR': ('First Solar', 'Information Technology'),
        'FE': ('FirstEnergy', 'Utilities'),
        'FISV': ('Fiserv', 'Financials'),
        'F': ('Ford Motor Company', 'Consumer Discretionary'),
        'FTNT': ('Fortinet', 'Information Technology'),
        'FTV': ('Fortive', 'Industrials'),
        'FOXA': ('Fox Corporation (Class A)', 'Communication Services'),
        'FOX': ('Fox Corporation (Class B)', 'Communication Services'),
        'BEN': ('Franklin Resources', 'Financials'),
        'FCX': ('Freeport-McMoRan', 'Materials'),
        'GRMN': ('Garmin', 'Consumer Discretionary'),
        'IT': ('Gartner', 'Information Technology'),
        'GEHC': ('GE HealthCare', 'Health Care'),
        'GEV': ('GE Vernova', 'Industrials'),
        'GEN': ('Gen Digital', 'Information Technology'),
        'GNRC': ('Generac', 'Industrials'),
        'GD': ('General Dynamics', 'Industrials'),
        'GIS': ('General Mills', 'Consumer Staples'),
        'GM': ('General Motors', 'Consumer Discretionary'),
        'GPC': ('Genuine Parts Company', 'Consumer Discretionary'),
        'GILD': ('Gilead Sciences', 'Health Care'),
        'GPN': ('Global Payments', 'Financials'),
        'GL': ('Globe Life', 'Financials'),
        'GDDY': ('GoDaddy', 'Information Technology'),
        'GS': ('Goldman Sachs', 'Financials'),
        'HAL': ('Halliburton', 'Energy'),
        'HIG': ('Hartford (The)', 'Financials'),
        'HAS': ('Hasbro', 'Consumer Discretionary'),
        'HCA': ('HCA Healthcare', 'Health Care'),
        'DOC': ('Healthpeak Properties', 'Real Estate'),
        'HSIC': ('Henry Schein', 'Health Care'),
        'HSY': ('Hershey Company (The)', 'Consumer Staples'),
        'HPE': ('Hewlett Packard Enterprise', 'Information Technology'),
        'HLT': ('Hilton Worldwide', 'Consumer Discretionary'),
        'HON': ('Honeywell', 'Industrials'),
        'HRL': ('Hormel Foods', 'Consumer Staples'),
        'HST': ('Host Hotels & Resorts', 'Real Estate'),
        'HWM': ('Howmet Aerospace', 'Industrials'),
        'HPQ': ('HP Inc.', 'Information Technology'),
        'HUBB': ('Hubbell Incorporated', 'Industrials'),
        'HUM': ('Humana', 'Health Care'),
        'HBAN': ('Huntington Bancshares', 'Financials'),
        'HII': ('Huntington Ingalls Industries', 'Industrials'),
        'IEX': ('IDEX Corporation', 'Industrials'),
        'IDXX': ('Idexx Laboratories', 'Health Care'),
        'ITW': ('Illinois Tool Works', 'Industrials'),
        'INCY': ('Incyte', 'Health Care'),
        'IR': ('Ingersoll Rand', 'Industrials'),
        'PODD': ('Insulet Corporation', 'Health Care'),
        'INTC': ('Intel', 'Information Technology'),
        'IBKR': ('Interactive Brokers', 'Financials'),
        'ICE': ('Intercontinental Exchange', 'Financials'),
        'IFF': ('International Flavors & Fragrances', 'Materials'),
        'IP': ('International Paper', 'Materials'),
        'INTU': ('Intuit', 'Information Technology'),
        'ISRG': ('Intuitive Surgical', 'Health Care'),
        'IVZ': ('Invesco', 'Financials'),
        'INVH': ('Invitation Homes', 'Real Estate'),
        'IQV': ('IQVIA', 'Health Care'),
        'IRM': ('Iron Mountain', 'Real Estate'),
        'JBHT': ('J.B. Hunt', 'Industrials'),
        'JBL': ('Jabil', 'Information Technology'),
        'JKHY': ('Jack Henry & Associates', 'Financials'),
        'J': ('Jacobs Solutions', 'Industrials'),
        'JCI': ('Johnson Controls', 'Industrials'),
        'KVUE': ('Kenvue', 'Consumer Staples'),
        'KDP': ('Keurig Dr Pepper', 'Consumer Staples'),
        'KEY': ('KeyCorp', 'Financials'),
        'KEYS': ('Keysight Technologies', 'Information Technology'),
        'KMB': ('Kimberly-Clark', 'Consumer Staples'),
        'KIM': ('Kimco Realty', 'Real Estate'),
        'KMI': ('Kinder Morgan', 'Energy'),
        'KKR': ('KKR & Co.', 'Financials'),
        'KLAC': ('KLA Corporation', 'Information Technology'),
        'KHC': ('Kraft Heinz', 'Consumer Staples'),
        'KR': ('Kroger', 'Consumer Staples'),
        'LHX': ('L3Harris', 'Industrials'),
        'LH': ('Labcorp', 'Health Care'),
        'LRCX': ('Lam Research', 'Information Technology'),
        'LVS': ('Las Vegas Sands', 'Consumer Discretionary'),
        'LDOS': ('Leidos', 'Industrials'),
        'LEN': ('Lennar', 'Consumer Discretionary'),
        'LII': ('Lennox International', 'Industrials'),
        'LYV': ('Live Nation Entertainment', 'Communication Services'),
        'LMT': ('Lockheed Martin', 'Industrials'),
        'L': ('Loews Corporation', 'Financials'),
        'LOW': ("Lowe's", 'Consumer Discretionary'),
        'LULU': ('Lululemon Athletica', 'Consumer Discretionary'),
        'LITE': ('Lumentum', 'Information Technology'),
        'LYB': ('LyondellBasell', 'Materials'),
        'MTB': ('M&T Bank', 'Financials'),
        'MPC': ('Marathon Petroleum', 'Energy'),
        'MAR': ('Marriott International', 'Consumer Discretionary'),
        'MRSH': ('Marsh McLennan', 'Financials'),
        'MLM': ('Martin Marietta Materials', 'Materials'),
        'MAS': ('Masco', 'Industrials'),
        'MKC': ('McCormick & Company', 'Consumer Staples'),
        'MCK': ('McKesson Corporation', 'Health Care'),
        'MDT': ('Medtronic', 'Health Care'),
        'MRK': ('Merck & Co.', 'Health Care'),
        'MET': ('MetLife', 'Financials'),
        'MTD': ('Mettler Toledo', 'Health Care'),
        'MGM': ('MGM Resorts', 'Consumer Discretionary'),
        'MCHP': ('Microchip Technology', 'Information Technology'),
        'MU': ('Micron Technology', 'Information Technology'),
        'MAA': ('Mid-America Apartment Communities', 'Real Estate'),
        'MRNA': ('Moderna', 'Health Care'),
        'TAP': ('Molson Coors Beverage Company', 'Consumer Staples'),
        'MDLZ': ('Mondelez International', 'Consumer Staples'),
        'MPWR': ('Monolithic Power Systems', 'Information Technology'),
        'MNST': ('Monster Beverage', 'Consumer Staples'),
        'MCO': ("Moody's Corporation", 'Financials'),
        'MS': ('Morgan Stanley', 'Financials'),
        'MOS': ('Mosaic Company (The)', 'Materials'),
        'MSI': ('Motorola Solutions', 'Information Technology'),
        'MSCI': ('MSCI Inc.', 'Financials'),
        'NDAQ': ('Nasdaq, Inc.', 'Financials'),
        'NTAP': ('NetApp', 'Information Technology'),
        'NEM': ('Newmont', 'Materials'),
        'NWSA': ('News Corp (Class A)', 'Communication Services'),
        'NWS': ('News Corp (Class B)', 'Communication Services'),
        'NEE': ('NextEra Energy', 'Utilities'),
        'NKE': ('Nike, Inc.', 'Consumer Discretionary'),
        'NI': ('NiSource', 'Utilities'),
        'NDSN': ('Nordson Corporation', 'Industrials'),
        'NSC': ('Norfolk Southern', 'Industrials'),
        'NTRS': ('Northern Trust', 'Financials'),
        'NOC': ('Northrop Grumman', 'Industrials'),
        'NCLH': ('Norwegian Cruise Line Holdings', 'Consumer Discretionary'),
        'NRG': ('NRG Energy', 'Utilities'),
        'NUE': ('Nucor', 'Materials'),
        'NVR': ('NVR, Inc.', 'Consumer Discretionary'),
        'NXPI': ('NXP Semiconductors', 'Information Technology'),
        'ORLY': ('O’Reilly Automotive', 'Consumer Discretionary'),
        'OXY': ('Occidental Petroleum', 'Energy'),
        'ODFL': ('Old Dominion', 'Industrials'),
        'OMC': ('Omnicom Group', 'Communication Services'),
        'ON': ('ON Semiconductor', 'Information Technology'),
        'OKE': ('Oneok', 'Energy'),
        'OTIS': ('Otis Worldwide', 'Industrials'),
        'PCAR': ('Paccar', 'Industrials'),
        'PKG': ('Packaging Corporation of America', 'Materials'),
        'PLTR': ('Palantir Technologies', 'Information Technology'),
        'PANW': ('Palo Alto Networks', 'Information Technology'),
        'PSKY': ('Paramount Skydance Corporation', 'Communication Services'),
        'PH': ('Parker Hannifin', 'Industrials'),
        'PAYX': ('Paychex', 'Industrials'),
        'PYPL': ('PayPal', 'Financials'),
        'PNR': ('Pentair', 'Industrials'),
        'PFE': ('Pfizer', 'Health Care'),
        'PCG': ('PG&E Corporation', 'Utilities'),
        'PM': ('Philip Morris International', 'Consumer Staples'),
        'PSX': ('Phillips 66', 'Energy'),
        'PNW': ('Pinnacle West Capital', 'Utilities'),
        'PNC': ('PNC Financial Services', 'Financials'),
        'POOL': ('Pool Corporation', 'Consumer Discretionary'),
        'PPG': ('PPG Industries', 'Materials'),
        'PPL': ('PPL Corporation', 'Utilities'),
        'PFG': ('Principal Financial Group', 'Financials'),
        'PGR': ('Progressive Corporation', 'Financials'),
        'PLD': ('Prologis', 'Real Estate'),
        'PRU': ('Prudential Financial', 'Financials'),
        'PEG': ('Public Service Enterprise Group', 'Utilities'),
        'PTC': ('PTC Inc.', 'Information Technology'),
        'PSA': ('Public Storage', 'Real Estate'),
        'PHM': ('PulteGroup', 'Consumer Discretionary'),
        'PWR': ('Quanta Services', 'Industrials'),
        'QCOM': ('Qualcomm', 'Information Technology'),
        'DGX': ('Quest Diagnostics', 'Health Care'),
        'Q': ('Qnity Electronics', 'Information Technology'),
        'RL': ('Ralph Lauren Corporation', 'Consumer Discretionary'),
        'RJF': ('Raymond James Financial', 'Financials'),
        'RTX': ('RTX Corporation', 'Industrials'),
        'O': ('Realty Income', 'Real Estate'),
        'REG': ('Regency Centers', 'Real Estate'),
        'REGN': ('Regeneron Pharmaceuticals', 'Health Care'),
        'RF': ('Regions Financial Corporation', 'Financials'),
        'RSG': ('Republic Services', 'Industrials'),
        'RMD': ('ResMed', 'Health Care'),
        'RVTY': ('Revvity', 'Health Care'),
        'HOOD': ('Robinhood Markets', 'Financials'),
        'ROK': ('Rockwell Automation', 'Industrials'),
        'ROL': ('Rollins, Inc.', 'Industrials'),
        'ROP': ('Roper Technologies', 'Information Technology'),
        'ROST': ('Ross Stores', 'Consumer Discretionary'),
        'RCL': ('Royal Caribbean Group', 'Consumer Discretionary'),
        'SPGI': ('S&P Global', 'Financials'),
        'SNDK': ('Sandisk', 'Information Technology'),
        'SBAC': ('SBA Communications', 'Real Estate'),
        'SLB': ('Schlumberger', 'Energy'),
        'STX': ('Seagate Technology', 'Information Technology'),
        'SRE': ('Sempra', 'Utilities'),
        'SHW': ('Sherwin-Williams', 'Materials'),
        'SPG': ('Simon Property Group', 'Real Estate'),
        'SWKS': ('Skyworks Solutions', 'Information Technology'),
        'SJM': ('J.M. Smucker Company (The)', 'Consumer Staples'),
        'SW': ('Smurfit Westrock', 'Materials'),
        'SNA': ('Snap-on', 'Industrials'),
        'SOLV': ('Solventum', 'Health Care'),
        'SO': ('Southern Company', 'Utilities'),
        'LUV': ('Southwest Airlines', 'Industrials'),
        'SWK': ('Stanley Black & Decker', 'Industrials'),
        'SBUX': ('Starbucks', 'Consumer Discretionary'),
        'STT': ('State Street Corporation', 'Financials'),
        'STLD': ('Steel Dynamics', 'Materials'),
        'STE': ('Steris', 'Health Care'),
        'SYK': ('Stryker Corporation', 'Health Care'),
        'SMCI': ('Supermicro', 'Information Technology'),
        'SYF': ('Synchrony Financial', 'Financials'),
        'SNPS': ('Synopsys', 'Information Technology'),
        'SYY': ('Sysco', 'Consumer Staples'),
        'TMUS': ('T-Mobile US', 'Communication Services'),
        'TROW': ('T. Rowe Price', 'Financials'),
        'TTWO': ('Take-Two Interactive', 'Communication Services'),
        'TPR': ('Tapestry, Inc.', 'Consumer Discretionary'),
        'TRGP': ('Targa Resources', 'Energy'),
        'TGT': ('Target Corporation', 'Consumer Staples'),
        'TEL': ('TE Connectivity', 'Information Technology'),
        'TDY': ('Teledyne Technologies', 'Information Technology'),
        'TER': ('Teradyne', 'Information Technology'),
        'TXN': ('Texas Instruments', 'Information Technology'),
        'TPL': ('Texas Pacific Land Corporation', 'Energy'),
        'TXT': ('Textron', 'Industrials'),
        'TJX': ('TJX Companies', 'Consumer Discretionary'),
        'TKO': ('TKO Group Holdings', 'Communication Services'),
        'TTD': ('Trade Desk (The)', 'Communication Services'),
        'TSCO': ('Tractor Supply', 'Consumer Discretionary'),
        'TT': ('Trane Technologies', 'Industrials'),
        'TDG': ('TransDigm Group', 'Industrials'),
        'TRV': ('Travelers Companies (The)', 'Financials'),
        'TRMB': ('Trimble Inc.', 'Information Technology'),
        'TFC': ('Truist Financial', 'Financials'),
        'TYL': ('Tyler Technologies', 'Information Technology'),
        'TSN': ('Tyson Foods', 'Consumer Staples'),
        'USB': ('U.S. Bancorp', 'Financials'),
        'UBER': ('Uber', 'Industrials'),
        'UDR': ('UDR, Inc.', 'Real Estate'),
        'ULTA': ('Ulta Beauty', 'Consumer Discretionary'),
        'UNP': ('Union Pacific Corporation', 'Industrials'),
        'UAL': ('United Airlines Holdings', 'Industrials'),
        'UPS': ('United Parcel Service', 'Industrials'),
        'URI': ('United Rentals', 'Industrials'),
        'UHS': ('Universal Health Services', 'Health Care'),
        'VLO': ('Valero Energy', 'Energy'),
        'VEEV': ('Veeva Systems', 'Health Care'),
        'VTR': ('Ventas', 'Real Estate'),
        'VLTO': ('Veralto', 'Industrials'),
        'VRSN': ('Verisign', 'Information Technology'),
        'VRSK': ('Verisk Analytics', 'Industrials'),
        'VZ': ('Verizon', 'Communication Services'),
        'VRTX': ('Vertex Pharmaceuticals', 'Health Care'),
        'VRT': ('Vertiv', 'Industrials'),
        'VTRS': ('Viatris', 'Health Care'),
        'VICI': ('Vici Properties', 'Real Estate'),
        'VST': ('Vistra Corp.', 'Utilities'),
        'VMC': ('Vulcan Materials Company', 'Materials'),
        'WRB': ('W. R. Berkley Corporation', 'Financials'),
        'GWW': ('W. W. Grainger', 'Industrials'),
        'WAB': ('Wabtec', 'Industrials'),
        'DIS': ('Walt Disney Company (The)', 'Communication Services'),
        'WBD': ('Warner Bros. Discovery', 'Communication Services'),
        'WM': ('Waste Management', 'Industrials'),
        'WAT': ('Waters Corporation', 'Health Care'),
        'WEC': ('WEC Energy Group', 'Utilities'),
        'WFC': ('Wells Fargo', 'Financials'),
        'WELL': ('Welltower', 'Real Estate'),
        'WST': ('West Pharmaceutical Services', 'Health Care'),
        'WDC': ('Western Digital', 'Information Technology'),
        'WY': ('Weyerhaeuser', 'Real Estate'),
        'WSM': ('Williams-Sonoma, Inc.', 'Consumer Discretionary'),
        'WMB': ('Williams Companies', 'Energy'),
        'WTW': ('Willis Towers Watson', 'Financials'),
        'WDAY': ('Workday, Inc.', 'Information Technology'),
        'WYNN': ('Wynn Resorts', 'Consumer Discretionary'),
        'XEL': ('Xcel Energy', 'Utilities'),
        'XYL': ('Xylem Inc.', 'Industrials'),
        'YUM': ('Yum! Brands', 'Consumer Discretionary'),
        'ZBRA': ('Zebra Technologies', 'Information Technology'),
        'ZBH': ('Zimmer Biomet', 'Health Care'),
        'ZTS': ('Zoetis', 'Health Care'),
        'ASML': ('ASML Holding', 'Information Technology'),
        'ARM': ('Arm Holdings', 'Information Technology'),
        'MRVL': ('Marvell Technology', 'Information Technology'),
        'SHOP': ('Shopify Inc.', 'Information Technology'),
        'PDD': ('PDD Holdings', 'Consumer Discretionary'),
        'MELI': ('MercadoLibre Inc.', 'Consumer Discretionary'),
        'FER': ('Ferrovial SE', 'Industrials'),
        'MSTR': ('Strategy Inc. (MicroStrategy)', 'Information Technology'),
        'CCEP': ('Coca-Cola Europacific Partners', 'Consumer Staples'),
        'ALNY': ('Alnylam Pharmaceuticals', 'Health Care'),
        'TRI': ('Thomson Reuters', 'Industrials'),
        'INSM': ('Insmed Inc.', 'Health Care'),
        'ZS': ('Zscaler Inc.', 'Information Technology'),
        'SPY': ('SPDR S&P 500 ETF Trust', 'ETF - Broad Market'),
        'QQQ': ('Invesco QQQ Trust', 'ETF - Broad Market'),
        'IWM': ('iShares Russell 2000 ETF', 'ETF - Broad Market'),
        'DIA': ('SPDR Dow Jones Industrial Average ETF', 'ETF - Broad Market'),
        'VTI': ('Vanguard Total Stock Market ETF', 'ETF - Broad Market'),
        'RSP': ('Invesco S&P 500 Equal Weight ETF', 'ETF - Broad Market'),
        'TQQQ': ('ProShares UltraPro QQQ 3x', 'ETF - Leveraged/Inverse'),
        'SQQQ': ('ProShares UltraPro Short QQQ -3x', 'ETF - Leveraged/Inverse'),
        'SOXL': ('Direxion Daily Semiconductor Bull 3x', 'ETF - Leveraged/Inverse'),
        'SOXS': ('Direxion Daily Semiconductor Bear 3x', 'ETF - Leveraged/Inverse'),
        'TNA': ('Direxion Daily Small Cap Bull 3x', 'ETF - Leveraged/Inverse'),
        'TZA': ('Direxion Daily Small Cap Bear 3x', 'ETF - Leveraged/Inverse'),
        'SPXL': ('Direxion Daily S&P 500 Bull 3x', 'ETF - Leveraged/Inverse'),
        'SPXU': ('ProShares UltraPro Short S&P 500', 'ETF - Leveraged/Inverse'),
        'SPXS': ('Direxion Daily S&P 500 Bear -3x', 'ETF - Leveraged/Inverse'),
        'UPRO': ('ProShares UltraPro S&P 500 3x', 'ETF - Leveraged/Inverse'),
        'SDOW': ('ProShares UltraPro Short Dow30 -3x', 'ETF - Leveraged/Inverse'),
        'FAS': ('Direxion Daily Financial Bull 3x', 'ETF - Leveraged/Inverse'),
        'FAZ': ('Direxion Daily Financial Bear 3x', 'ETF - Leveraged/Inverse'),
        'LABU': ('Direxion Daily S&P Biotech Bull 3x', 'ETF - Leveraged/Inverse'),
        'LABD': ('Direxion Daily S&P Biotech Bear 3x', 'ETF - Leveraged/Inverse'),
        'YINN': ('Direxion Daily FTSE China Bull 3x', 'ETF - Leveraged/Inverse'),
        'YANG': ('Direxion Daily FTSE China Bear -3x', 'ETF - Leveraged/Inverse'),
        'TMF': ('Direxion Daily 20+ Yr Treasury Bull 3x', 'ETF - Leveraged/Inverse'),
        'TBT': ('ProShares UltraShort 20+ Yr Treasury -2x', 'ETF - Leveraged/Inverse'),
        'DPST': ('Direxion Daily Regional Banks Bull 3x', 'ETF - Leveraged/Inverse'),
        'NUGT': ('Direxion Daily Gold Miners Bull 2x', 'ETF - Leveraged/Inverse'),
        'JNUG': ('Direxion Daily Junior Gold Miners Bull 2x', 'ETF - Leveraged/Inverse'),
        'GUSH': ('Direxion Daily S&P O&G Exp&Prod Bull 2x', 'ETF - Leveraged/Inverse'),
        'ERX': ('Direxion Daily Energy Bull 2x', 'ETF - Leveraged/Inverse'),
        'KOLD': ('ProShares UltraShort Bloomberg Natural Gas -2x', 'ETF - Leveraged/Inverse'),
        'BOIL': ('ProShares Ultra Bloomberg Natural Gas 2x', 'ETF - Leveraged/Inverse'),
        'UCO': ('ProShares Ultra Bloomberg Crude Oil 2x', 'ETF - Leveraged/Inverse'),
        'TSLL': ('Direxion Daily TSLA Bull 1.5x', 'ETF - Leveraged/Inverse'),
        'NVDS': ('AXS 1.25x NVDA Bear Daily ETF', 'ETF - Leveraged/Inverse'),
        'SDS': ('ProShares UltraShort S&P500 -2x', 'ETF - Leveraged/Inverse'),
        'SH': ('ProShares Short S&P500 -1x', 'ETF - Leveraged/Inverse'),
        'UVXY': ('ProShares Ultra VIX ST Futures 2x', 'ETF - Volatility'),
        'VXX': ('iPath S&P 500 VIX ST Futures ETN', 'ETF - Volatility'),
        'UVIX': ('2x Long VIX Futures ETF', 'ETF - Volatility'),
        'VIXY': ('ProShares VIX Short-Term Futures ETF', 'ETF - Volatility'),
        'SVXY': ('ProShares Short VIX ST Futures -1x', 'ETF - Volatility'),
        'GLD': ('SPDR Gold Shares', 'ETF - Commodity'),
        'SLV': ('iShares Silver Trust', 'ETF - Commodity'),
        'IAU': ('iShares Gold Trust', 'ETF - Commodity'),
        'GDX': ('VanEck Gold Miners ETF', 'ETF - Commodity'),
        'GDXJ': ('VanEck Junior Gold Miners ETF', 'ETF - Commodity'),
        'SILJ': ('ETFMG Prime Junior Silver Miners ETF', 'ETF - Commodity'),
        'USO': ('United States Oil Fund', 'ETF - Commodity'),
        'UNG': ('United States Natural Gas Fund', 'ETF - Commodity'),
        'URA': ('Global X Uranium ETF', 'ETF - Commodity'),
        'URNM': ('Sprott Uranium Miners ETF', 'ETF - Commodity'),
        'TLT': ('iShares 20+ Year Treasury Bond ETF', 'ETF - Fixed Income'),
        'HYG': ('iShares iBoxx USD High Yield Corp Bond ETF', 'ETF - Fixed Income'),
        'LQD': ('iShares iBoxx USD Investment Grade Corp Bond ETF', 'ETF - Fixed Income'),
        'IEF': ('iShares 7-10 Year Treasury Bond ETF', 'ETF - Fixed Income'),
        'EMB': ('iShares J.P. Morgan USD EM Bond ETF', 'ETF - Fixed Income'),
        'XLF': ('Financial Select Sector SPDR', 'ETF - Sector Equity'),
        'XLE': ('Energy Select Sector SPDR', 'ETF - Sector Equity'),
        'XLI': ('Industrial Select Sector SPDR', 'ETF - Sector Equity'),
        'XLU': ('Utilities Select Sector SPDR', 'ETF - Sector Equity'),
        'XLP': ('Consumer Staples Select Sector SPDR', 'ETF - Sector Equity'),
        'XLK': ('Technology Select Sector SPDR', 'ETF - Sector Equity'),
        'XLV': ('Health Care Select Sector SPDR', 'ETF - Sector Equity'),
        'XLY': ('Consumer Discretionary Select Sector SPDR', 'ETF - Sector Equity'),
        'XLB': ('Materials Select Sector SPDR', 'ETF - Sector Equity'),
        'XLC': ('Communication Services Select Sector SPDR', 'ETF - Sector Equity'),
        'KRE': ('SPDR S&P Regional Banking ETF', 'ETF - Sector Equity'),
        'KBE': ('SPDR S&P Bank ETF', 'ETF - Sector Equity'),
        'SMH': ('VanEck Semiconductor ETF', 'ETF - Sector Equity'),
        'XBI': ('SPDR S&P Biotech ETF', 'ETF - Sector Equity'),
        'IBB': ('iShares Biotechnology ETF', 'ETF - Sector Equity'),
        'XOP': ('SPDR Oil & Gas Exploration & Production ETF', 'ETF - Sector Equity'),
        'OIH': ('VanEck Oil Services ETF', 'ETF - Sector Equity'),
        'ITB': ('iShares U.S. Home Construction ETF', 'ETF - Sector Equity'),
        'XHB': ('SPDR S&P Homebuilders ETF', 'ETF - Sector Equity'),
        'XRT': ('SPDR S&P Retail ETF', 'ETF - Sector Equity'),
        'IYR': ('iShares U.S. Real Estate ETF', 'ETF - Sector Equity'),
        'ARKK': ('ARK Innovation ETF', 'ETF - Sector Equity'),
        'ARKG': ('ARK Genomic Revolution ETF', 'ETF - Sector Equity'),
        'ICLN': ('iShares Global Clean Energy ETF', 'ETF - Sector Equity'),
        'TAN': ('Invesco Solar ETF', 'ETF - Sector Equity'),
        'MSOS': ('AdvisorShares Pure US Cannabis ETF', 'ETF - Sector Equity'),
        'JETS': ('U.S. Global Jets ETF', 'ETF - Sector Equity'),
        'XME': ('SPDR S&P Metals & Mining ETF', 'ETF - Sector Equity'),
        'IHI': ('iShares U.S. Medical Devices ETF', 'ETF - Sector Equity'),
        'SCHD': ('Schwab US Dividend Equity ETF', 'ETF - Sector Equity'),
        'EEM': ('iShares MSCI Emerging Markets ETF', 'ETF - International/EM'),
        'EWZ': ('iShares MSCI Brazil ETF', 'ETF - International/EM'),
        'FXI': ('iShares China Large-Cap ETF', 'ETF - International/EM'),
        'EFA': ('iShares MSCI EAFE ETF', 'ETF - International/EM'),
        'KWEB': ('KraneShares CSI China Internet ETF', 'ETF - International/EM'),
        'ASHR': ('Xtrackers Harvest CSI 300 China A-Shares ETF', 'ETF - International/EM'),
        'EWJ': ('iShares MSCI Japan ETF', 'ETF - International/EM'),
        'EWA': ('iShares MSCI Australia ETF', 'ETF - International/EM'),
        'EWG': ('iShares MSCI Germany ETF', 'ETF - International/EM'),
        'INDA': ('iShares MSCI India ETF', 'ETF - International/EM'),
        'FEZ': ('SPDR EURO STOXX 50 ETF', 'ETF - International/EM'),
        'UUP': ('Invesco DB US Dollar Index Bullish Fund', 'ETF - Currency'),
        'BITO': ('ProShares Bitcoin Strategy ETF', 'ETF - Crypto'),
    },
    "HK": {
        '0700.HK': ('Tencent Holdings', 'Information Technology'),
        '9988.HK': ('Alibaba Group', 'Consumer Discretionary'),
        '0941.HK': ('China Mobile', 'Information Technology'),
        '1299.HK': ('AIA Group', 'Financials'),
        '0005.HK': ('HSBC Holdings', 'Financials'),
        '0939.HK': ('China Construction Bank', 'Financials'),
        '1398.HK': ('ICBC', 'Financials'),
        '3690.HK': ('Meituan', 'Consumer Discretionary'),
        '0883.HK': ('CNOOC', 'Energy'),
        '0857.HK': ('PetroChina', 'Energy'),
        '1810.HK': ('Xiaomi Corp.', 'Information Technology'),
        '2318.HK': ('Ping An Insurance', 'Financials'),
        '1928.HK': ('Sands China', 'Consumer Discretionary'),
        '0027.HK': ('Galaxy Entertainment', 'Consumer Discretionary'),
        '0688.HK': ('China Overseas Land', 'Real Estate'),
        '0016.HK': ('SHK Properties', 'Real Estate'),
        '0001.HK': ('CK Hutchison Holdings', 'Industrials'),
        '0003.HK': ('Hong Kong & China Gas', 'Utilities'),
        '0006.HK': ('Power Assets Holdings', 'Utilities'),
        '0011.HK': ('Hang Seng Bank', 'Financials'),
        '0012.HK': ('Henderson Land Development', 'Real Estate'),
        '0017.HK': ('New World Development', 'Real Estate'),
        '0066.HK': ('MTR Corporation', 'Industrials'),
        '0101.HK': ('Hang Lung Properties', 'Real Estate'),
        '0175.HK': ('Geely Automobile', 'Consumer Discretionary'),
        '0267.HK': ('CITIC Limited', 'Financials'),
        '0288.HK': ('WH Group', 'Consumer Staples'),
        '0322.HK': ('Tingyi (Cayman Islands)', 'Consumer Staples'),
        '0386.HK': ('Sinopec Corp', 'Energy'),
        '0388.HK': ('Hong Kong Exchanges & Clearing', 'Financials'),
        '0669.HK': ('Techtronic Industries', 'Industrials'),
        '0762.HK': ('China Unicom', 'Information Technology'),
        '0823.HK': ('Link REIT', 'Real Estate'),
        '0868.HK': ('Xinyi Glass Holdings', 'Industrials'),
        '0960.HK': ('Longfor Group', 'Real Estate'),
        '0992.HK': ('Lenovo Group', 'Information Technology'),
        '1038.HK': ('CK Infrastructure Holdings', 'Industrials'),
        '1044.HK': ('Hengan International', 'Consumer Staples'),
        '1093.HK': ('CSPC Pharmaceutical Group', 'Health Care'),
        '1109.HK': ('China Resources Land', 'Real Estate'),
        '1113.HK': ('CK Asset Holdings', 'Real Estate'),
        '1177.HK': ('Sino Biopharmaceutical', 'Health Care'),
        '1211.HK': ('BYD Company', 'Industrials'),
        '1339.HK': ('PICC Group', 'Financials'),
        '2269.HK': ('WuXi Biologics', 'Health Care'),
        '2313.HK': ('Shenzhou International', 'Consumer Staples'),
        '2331.HK': ('Li Ning Company', 'Consumer Staples'),
        '2382.HK': ('Sunny Optical Technology', 'Information Technology'),
        '2628.HK': ('China Life Insurance', 'Financials'),
        '3328.HK': ('Bank of Communications', 'Financials'),
        '6618.HK': ('JD Health International', 'Health Care'),
        '9618.HK': ('JD.com', 'Consumer Discretionary'),
        '9999.HK': ('NetEase', 'Consumer Discretionary'),
    },
    "JP": {
        '7203.T': ('Toyota Motor', 'Industrials'),
        '6758.T': ('Sony Group', 'Information Technology'),
        '9984.T': ('SoftBank Group', 'Information Technology'),
        '8306.T': ('Mitsubishi UFJ Financial', 'Financials'),
        '6098.T': ('Recruit Holdings', 'Consumer Discretionary'),
        '9432.T': ('NTT Corp.', 'Information Technology'),
        '6501.T': ('Hitachi Ltd.', 'Information Technology'),
        '7974.T': ('Nintendo Co.', 'Consumer Discretionary'),
        '4063.T': ('Shin-Etsu Chemical', 'Information Technology'),
        '8035.T': ('Tokyo Electron', 'Information Technology'),
        '6981.T': ('Murata Manufacturing', 'Information Technology'),
        '9433.T': ('KDDI Corp.', 'Information Technology'),
        '7267.T': ('Honda Motor', 'Industrials'),
        '8316.T': ('Sumitomo Mitsui Financial', 'Financials'),
        '4502.T': ('Takeda Pharmaceutical', 'Health Care'),
        '6502.T': ('Toshiba Corp.', 'Information Technology'),
        '6861.T': ('Keyence Corp.', 'Information Technology'),
        '8058.T': ('Mitsubishi Corp.', 'Industrials'),
        '8001.T': ('Itochu Corp.', 'Industrials'),
        '8031.T': ('Mitsui & Co.', 'Industrials'),
        '8053.T': ('Sumitomo Corp.', 'Industrials'),
        '9983.T': ('Fast Retailing', 'Consumer Discretionary'),
        '4661.T': ('Oriental Land', 'Consumer Discretionary'),
        '6594.T': ('Nidec Corp.', 'Information Technology'),
        '6857.T': ('Advantest Corp.', 'Information Technology'),
        '8801.T': ('Mitsui Fudosan', 'Real Estate'),
        '8802.T': ('Mitsubishi Estate', 'Real Estate'),
        '9020.T': ('East Japan Railway', 'Industrials'),
        '9022.T': ('Central Japan Railway', 'Industrials'),
        '9101.T': ('Nippon Yusen (NYK Line)', 'Industrials'),
        '9104.T': ('Mitsui O.S.K. Lines', 'Industrials'),
        '4503.T': ('Astellas Pharma', 'Health Care'),
        '4519.T': ('Chugai Pharmaceutical', 'Health Care'),
        '4568.T': ('Daiichi Sankyo', 'Health Care'),
        '4543.T': ('Terumo Corp.', 'Health Care'),
        '6273.T': ('SMC Corp.', 'Industrials'),
        '6301.T': ('Komatsu Ltd.', 'Industrials'),
        '6326.T': ('Kubota Corp.', 'Industrials'),
        '6367.T': ('Daikin Industries', 'Industrials'),
        '6702.T': ('Fujitsu Ltd.', 'Information Technology'),
        '6752.T': ('Panasonic Holdings', 'Information Technology'),
        '6770.T': ('Alps Alpine', 'Information Technology'),
        '6920.T': ('Lasertec Corp.', 'Information Technology'),
        '6971.T': ('Kyocera Corp.', 'Information Technology'),
        '7011.T': ('Mitsubishi Heavy Industries', 'Industrials'),
        '7269.T': ('Suzuki Motor', 'Industrials'),
        '7270.T': ('Subaru Corp.', 'Industrials'),
        '7733.T': ('Olympus Corp.', 'Health Care'),
        '7735.T': ('SCREEN Holdings', 'Information Technology'),
        '7751.T': ('Canon Inc.', 'Information Technology'),
        '7832.T': ('Bandai Namco Holdings', 'Consumer Discretionary'),
        '8267.T': ('Aeon Co.', 'Consumer Discretionary'),
        '8411.T': ('Mizuho Financial Group', 'Financials'),
        '8591.T': ('Orix Corp.', 'Financials'),
        '8604.T': ('Nomura Holdings', 'Financials'),
        '8630.T': ('Sompo Holdings', 'Financials'),
        '8725.T': ('MS&AD Insurance Group', 'Financials'),
        '8750.T': ('Dai-ichi Life Holdings', 'Financials'),
        '8766.T': ('Tokio Marine Holdings', 'Financials'),
        '9201.T': ('Japan Airlines', 'Industrials'),
        '9202.T': ('ANA Holdings', 'Industrials'),
        '9434.T': ('SoftBank Corp.', 'Information Technology'),
        '9613.T': ('NTT Data Group', 'Information Technology'),
        '2502.T': ('Asahi Group Holdings', 'Consumer Staples'),
        '2503.T': ('Kirin Holdings', 'Consumer Staples'),
        '2802.T': ('Ajinomoto Co.', 'Consumer Staples'),
        '2914.T': ('Japan Tobacco', 'Consumer Staples'),
        '3382.T': ('Seven & I Holdings', 'Consumer Discretionary'),
        '4307.T': ('Nomura Research Institute', 'Information Technology'),
        '4452.T': ('Kao Corp.', 'Consumer Staples'),
        '4901.T': ('Fujifilm Holdings', 'Information Technology'),
        '4911.T': ('Shiseido Co.', 'Consumer Staples'),
        '5108.T': ('Bridgestone Corp.', 'Industrials'),
        '5401.T': ('Nippon Steel', 'Materials'),
        '5713.T': ('Sumitomo Metal Mining', 'Materials'),
        '5802.T': ('Sumitomo Electric Industries', 'Information Technology'),
        '6504.T': ('Fuji Electric', 'Information Technology'),
        '6645.T': ('Omron Corp.', 'Information Technology'),
        '6963.T': ('Rohm Co.', 'Information Technology'),
        '7186.T': ('Concordia Financial Group', 'Financials'),
        '7201.T': ('Nissan Motor', 'Industrials'),
        '7261.T': ('Mazda Motor', 'Industrials'),
        '7741.T': ('Hoya Corp.', 'Information Technology'),
        '8233.T': ('Takashimaya Co.', 'Consumer Discretionary'),
        '8252.T': ('Marui Group', 'Consumer Discretionary'),
        '8308.T': ('Resona Holdings', 'Financials'),
        '8331.T': ('The Chiba Bank', 'Financials'),
        '9531.T': ('Tokyo Gas', 'Utilities'),
        '9501.T': ('Tokyo Electric Power Holdings', 'Utilities'),
        '9503.T': ('Kansai Electric Power', 'Utilities'),
    },
    "KR": {
        '005930.KS': ('Samsung Electronics', 'Information Technology'),
        '000660.KS': ('SK Hynix', 'Information Technology'),
        '005380.KS': ('Hyundai Motor', 'Industrials'),
        '035420.KS': ('Naver Corp.', 'Information Technology'),
        '051910.KS': ('LG Chem', 'Industrials'),
        '006400.KS': ('Samsung SDI', 'Information Technology'),
        '035720.KS': ('Kakao Corp.', 'Information Technology'),
        '105560.KS': ('KB Financial Group', 'Financials'),
        '055550.KS': ('Shinhan Financial Group', 'Financials'),
        '012330.KS': ('Hyundai Mobis', 'Industrials'),
        '003550.KS': ('LG Corp.', 'Information Technology'),
        '066570.KS': ('LG Electronics', 'Information Technology'),
        '000270.KS': ('Kia Corp.', 'Industrials'),
        '009150.KS': ('Samsung Electro-Mechanics', 'Information Technology'),
        '010130.KS': ('Korea Zinc', 'Materials'),
        '011200.KS': ('HMM Co.', 'Industrials'),
        '011170.KS': ('Lotte Chemical', 'Materials'),
        '015760.KS': ('KEPCO', 'Utilities'),
        '017670.KS': ('SK Telecom', 'Information Technology'),
        '018260.KS': ('Samsung SDS', 'Information Technology'),
        '021240.KS': ('Coway Co.', 'Consumer Staples'),
        '024110.KS': ('Industrial Bank of Korea', 'Financials'),
        '028260.KS': ('Samsung C&T', 'Industrials'),
        '032830.KS': ('Samsung Life Insurance', 'Financials'),
        '033780.KS': ('KT&G Corp.', 'Consumer Staples'),
        '034220.KS': ('LG Display', 'Information Technology'),
        '034730.KS': ('SK Inc.', 'Industrials'),
        '035250.KS': ('Kangwon Land', 'Consumer Discretionary'),
        '036570.KS': ('NCsoft Corp.', 'Consumer Discretionary'),
        '051900.KS': ('LG Household & Health Care', 'Consumer Staples'),
        '000720.KS': ('Hyundai Engineering & Construction', 'Industrials'),
        '064350.KS': ('Hyundai Rotem', 'Industrials'),
        '068270.KS': ('Celltrion Inc.', 'Health Care'),
        '086790.KS': ('Hana Financial Group', 'Financials'),
        '090430.KS': ('Amorepacific Corp.', 'Consumer Staples'),
        '096770.KS': ('SK Innovation', 'Energy'),
        '207940.KS': ('Samsung Biologics', 'Health Care'),
        '259960.KS': ('Krafton Inc.', 'Consumer Discretionary'),
        '352820.KS': ('Hybe Co.', 'Consumer Discretionary'),
        '373220.KS': ('LG Energy Solution', 'Information Technology'),
        '000810.KS': ('Samsung Fire & Marine Insurance', 'Financials'),
        '010950.KS': ('S-Oil Corp.', 'Energy'),
        '003490.KS': ('Korean Air Lines', 'Industrials'),
    },
    "CN": {
        '600519.SS': ('Kweichow Moutai', 'Consumer Staples'),
        '601318.SS': ('Ping An Insurance', 'Financials'),
        '600036.SS': ('China Merchants Bank', 'Financials'),
        '601398.SS': ('ICBC', 'Financials'),
        '600028.SS': ('Sinopec', 'Energy'),
        '601988.SS': ('Bank of China', 'Financials'),
        '000858.SZ': ('Wuliangye Yibin', 'Consumer Staples'),
        '300750.SZ': ('CATL', 'Information Technology'),
        '002594.SZ': ('BYD Company', 'Industrials'),
        '600276.SS': ('Jiangsu Hengrui Medicine', 'Health Care'),
        '601166.SS': ('Industrial Bank', 'Financials'),
        '600900.SS': ('China Yangtze Power', 'Energy'),
        '600030.SS': ('CITIC Securities', 'Financials'),
        '601288.SS': ('Agricultural Bank of China', 'Financials'),
        '601328.SS': ('Bank of Communications', 'Financials'),
        '601601.SS': ('China Pacific Insurance', 'Financials'),
        '601628.SS': ('China Life Insurance', 'Financials'),
        '600000.SS': ('Shanghai Pudong Development Bank', 'Financials'),
        '600016.SS': ('China Minsheng Bank', 'Financials'),
        '601009.SS': ('Bank of Nanjing', 'Financials'),
        '600837.SS': ('Haitong Securities', 'Financials'),
        '000001.SZ': ('Ping An Bank', 'Financials'),
        '000333.SZ': ('Midea Group', 'Information Technology'),
        '000651.SZ': ('Gree Electric Appliances', 'Information Technology'),
        '002415.SZ': ('Hikvision', 'Information Technology'),
        '002475.SZ': ('Luxshare Precision Industry', 'Information Technology'),
        '300059.SZ': ('East Money Information', 'Financials'),
        '600585.SS': ('Anhui Conch Cement', 'Materials'),
        '601088.SS': ('China Shenhua Energy', 'Energy'),
        '601857.SS': ('PetroChina (A)', 'Energy'),
        '600050.SS': ('China Unicom (A)', 'Information Technology'),
        '600104.SS': ('SAIC Motor', 'Industrials'),
        '601238.SS': ('GAC Group', 'Industrials'),
        '000625.SZ': ('Chongqing Changan Automobile', 'Industrials'),
        '601633.SS': ('Great Wall Motor', 'Industrials'),
        '600660.SS': ('Fuyao Glass Industry', 'Industrials'),
        '601728.SS': ('China Telecom', 'Information Technology'),
        '600941.SS': ('China Mobile (A)', 'Information Technology'),
        '603259.SS': ('WuXi AppTec (A)', 'Health Care'),
        '300760.SZ': ('Mindray Medical', 'Health Care'),
        '600196.SS': ('Shanghai Fosun Pharmaceutical', 'Health Care'),
        '601111.SS': ('Air China', 'Industrials'),
        '600029.SS': ('China Southern Airlines', 'Industrials'),
        '601788.SS': ('Everbright Securities', 'Financials'),
        '601919.SS': ('COSCO Shipping Holdings', 'Industrials'),
        '600309.SS': ('Wanhua Chemical Group', 'Materials'),
        '601012.SS': ('LONGi Green Energy', 'Information Technology'),
        '300014.SZ': ('EVE Energy', 'Information Technology'),
        '600031.SS': ('Sany Heavy Industry', 'Industrials'),
        '000776.SZ': ('GF Securities', 'Financials'),
        '601225.SS': ('Shaanxi Coal Industry', 'Energy'),
        '600886.SS': ('SDIC Power Holdings', 'Utilities'),
        '601877.SS': ('Zhejiang Chint Electrics', 'Information Technology'),
    },
    "DE": {
        'SAP.DE': ('SAP SE', 'Information Technology'),
        'SIE.DE': ('Siemens AG', 'Industrials'),
        'DTE.DE': ('Deutsche Telekom AG', 'Communication Services'),
        'AIR.DE': ('Airbus SE', 'Industrials'),
        'ALV.DE': ('Allianz SE', 'Financials'),
        'VOW3.DE': ('Volkswagen AG', 'Consumer Discretionary'),
        'MBG.DE': ('Mercedes-Benz Group AG', 'Consumer Discretionary'),
        'BMW.DE': ('BMW AG', 'Consumer Discretionary'),
        'BAS.DE': ('BASF SE', 'Materials'),
        'IFX.DE': ('Infineon Technologies AG', 'Information Technology'),
        'DBK.DE': ('Deutsche Bank AG', 'Financials'),
        'DPW.DE': ('Deutsche Post AG', 'Industrials'),
        'MUV2.DE': ('Munich Re', 'Financials'),
        'HEN3.DE': ('Henkel AG & Co. KGaA', 'Consumer Staples'),
        'BAYN.DE': ('Bayer AG', 'Health Care'),
        'DB1.DE': ('Deutsche Börse AG', 'Financials'),
    },
    "FR": {
        'MC.PA': ('LVMH Moët Hennessy Louis Vuitton SE', 'Consumer Discretionary'),
        'TTE.PA': ('TotalEnergies SE', 'Energy'),
        'OR.PA': ("L'Oréal S.A.", 'Consumer Staples'),
        'RMS.PA': ('Hermès International S.A.', 'Consumer Discretionary'),
        'SGO.PA': ('Saint-Gobain', 'Industrials'),
        'SAN.PA': ('Sanofi', 'Health Care'),
        'AIR.PA': ('Airbus SE', 'Industrials'),
        'BNP.PA': ('BNP Paribas', 'Financials'),
        'ACA.PA': ('Crédit Agricole S.A.', 'Financials'),
        'AXA.PA': ('AXA SA', 'Financials'),
        'KER.PA': ('Kering SA', 'Consumer Discretionary'),
        'SU.PA': ('Schneider Electric S.E.', 'Industrials'),
        'DG.PA': ('Vinci SA', 'Industrials'),
        'STM.PA': ('STMicroelectronics N.V.', 'Information Technology'),
        'EL.PA': ('EssilorLuxottica', 'Health Care'),
        'AI.PA': ('Air Liquide', 'Materials'),
    },
    "GB": {
        'SHEL.L': ('Shell plc', 'Energy'),
        'AZN.L': ('AstraZeneca PLC', 'Health Care'),
        'HSBA.L': ('HSBC Holdings plc', 'Financials'),
        'ULVR.L': ('Unilever PLC', 'Consumer Staples'),
        'DGE.L': ('Diageo plc', 'Consumer Staples'),
        'BP.L': ('BP p.l.c.', 'Energy'),
        'RIO.L': ('Rio Tinto Group', 'Materials'),
        'GLEN.L': ('Glencore plc', 'Materials'),
        'BATS.L': ('British American Tobacco p.l.c.', 'Consumer Staples'),
        'NG.L': ('National Grid plc', 'Utilities'),
        'GSK.L': ('GSK plc', 'Health Care'),
        'REL.L': ('RELX PLC', 'Industrials'),
        'LLOY.L': ('Lloyds Banking Group plc', 'Financials'),
        'BARC.L': ('Barclays PLC', 'Financials'),
        'PRU.L': ('Prudential plc', 'Financials'),
        'VOD.L': ('Vodafone Group Plc', 'Communication Services'),
    },
    "TH": {
        'PTT.BK': ('PTT', 'Energy'),
        'PTTEP.BK': ('PTTEP', 'Energy'),
        'GULF.BK': ('Gulf Energy', 'Utilities'),
        'AOT.BK': ('Airports of Thailand', 'Industrials'),
        'ADVANC.BK': ('Advanced Info Service', 'Communication Services'),
        'TRUE.BK': ('True Corporation', 'Communication Services'),
        'DELTA.BK': ('Delta Electronics Thailand', 'Information Technology'),
        'CPALL.BK': ('CP All', 'Consumer Staples'),
        'BDMS.BK': ('Bangkok Dusit Medical', 'Health Care'),
        'BH.BK': ('Bumrungrad Hospital', 'Health Care'),
        'BBL.BK': ('Bangkok Bank', 'Financials'),
        'KBANK.BK': ('Kasikornbank', 'Financials'),
        'SCB.BK': ('SCB X', 'Financials'),
        'KTB.BK': ('Krung Thai Bank', 'Financials'),
        'SCC.BK': ('Siam Cement', 'Materials'),
        'TOP.BK': ('Thai Oil', 'Energy'),
        'GPSC.BK': ('Global Power Synergy', 'Utilities'),
        'INTUCH.BK': ('Intouch Holdings', 'Communication Services'),
        'HMPRO.BK': ('Home Product Center', 'Consumer Discretionary'),
        'MINT.BK': ('Minor International', 'Consumer Discretionary'),
        'CPF.BK': ('Charoen Pokphand Foods', 'Consumer Staples'),
        'MTC.BK': ('Muangthai Capital', 'Financials'),
        'OR.BK': ('PTT Oil and Retail', 'Consumer Discretionary'),
        'IVL.BK': ('Indorama Ventures', 'Materials'),
        'BEM.BK': ('Bangkok Expressway', 'Industrials'),
        'WHA.BK': ('WHA Corporation', 'Real Estate'),
        'CPN.BK': ('Central Pattana', 'Real Estate'),
        'EA.BK': ('Energy Absolute', 'Utilities'),
        'KCE.BK': ('KCE Electronics', 'Information Technology'),
        'COM7.BK': ('Com7', 'Consumer Discretionary'),
    },
}

RRG_US_SECTORS = {
    ticker: meta['sub']
    for ticker, meta in ETF_META.items()
    if meta.get('cat') == 'Sector'
}

RRG_US_THEMES = {
    ticker: meta['sub']
    for ticker, meta in ETF_META.items()
    if meta.get('cat') == 'Thematic'
}

RRG_GLOBAL_UNIVERSE = {
    'VT': ('Total World', 'Global'),
    'SPY': ('USA (S&P 500)', 'US'),
    'EWJ': ('Japan (Nikkei)', 'JP'),
    'MCHI': ('China (MSCI)', 'CN'),
    'EWG': ('Germany (DAX)', 'DE'),
    'EWU': ('UK (FTSE)', 'GB'),
    'EWQ': ('France (CAC)', 'FR'),
    'INDA': ('India (Nifty)', 'IN'),
    'EWY': ('South Korea (KOSPI)', 'KR'),
    'EWH': ('Hong Kong (Hang Seng)', 'HK'),
    'THD': ('Thailand (SET)', 'TH'),
    'EWZ': ('Brazil (Bovespa)', 'EM'),
    'GLD': ('Gold', 'Commodity'),
    'SLV': ('Silver', 'Commodity'),
    'USO': ('Crude Oil', 'Commodity'),
    'TLT': ('US Bonds 20Y+', 'Bonds'),
    'HYG': ('High-Yield Bonds', 'Bonds'),
    'UUP': ('US Dollar', 'Currency'),
    'VXX': ('Volatility (VIX)', 'Volatility'),
}

BENCHMARK = {
    'US': '^GSPC',
    'HK': '^HSI',
    'JP': '^N225',
    'KR': '^KS11',
    'CN': '000300.SS',
    'DE': '^GDAXI',
    'FR': '^FCHI',
    'GB': '^FTSE',
    'TH': '^SET.BK',
    'GLOBAL': 'VT',
    'US_SECTORS': 'SPY',
    'US_THEMES': 'SPY',
}

FLAGS = {
    "US": "🇺🇸", "TH": "🇹🇭", "HK": "🇭🇰", "JP": "🇯🇵", "KR": "🇰🇷", "CN": "🇨🇳",
    "DE": "🇩🇪", "FR": "🇫🇷", "GB": "🇬🇧"
}

